<?xml version="1.0" encoding="utf-8"?><Database Name="Library" Class="DataLibraryDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\SQLEXPRESS;Initial Catalog=Library;Integrated Security=True" SettingsObjectName="BDProj.Properties.Settings" SettingsPropertyName="LibraryConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Author" Member="Authors">
    <Type Name="Author">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Firstname" Type="System.String" DbType="NVarChar(63) NOT NULL" CanBeNull="false" />
      <Column Name="Lastname" Type="System.String" DbType="NVarChar(63) NOT NULL" CanBeNull="false" />
      <Association Name="Author_AuthorList" Member="AuthorLists" ThisKey="Id" OtherKey="AuthorId" Type="AuthorList" />
    </Type>
  </Table>
  <Table Name="dbo.Book" Member="Books">
    <Type Name="Book">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(63) NOT NULL" CanBeNull="false" />
      <Column Name="ISBN" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="Genre" Type="System.String" DbType="NVarChar(31)" CanBeNull="true" />
      <Column Name="DateOfAdd" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Association Name="Book_Copy" Member="Copies" ThisKey="Id" OtherKey="BookId" Type="Copy" />
      <Association Name="Book_AuthorList" Member="AuthorLists" ThisKey="Id" OtherKey="BookId" Type="AuthorList" />
    </Type>
  </Table>
  <Table Name="dbo.Borrowings" Member="Borrowings">
    <Type Name="Borrowing">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CopyId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BorrowDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="BorrowDays" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ReturnDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Association Name="User_Borrowing" Member="User" ThisKey="UserId" OtherKey="Id" Type="User" IsForeignKey="true" />
      <Association Name="Copy_Borrowing" Member="Copy" ThisKey="CopyId" OtherKey="Id" Type="Copy" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Firstname" Type="System.String" DbType="NVarChar(63) NOT NULL" CanBeNull="false" />
      <Column Name="Lastname" Type="System.String" DbType="NVarChar(63) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(63) NOT NULL" CanBeNull="false" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(63) NOT NULL" CanBeNull="false" />
      <Column Name="City" Type="System.String" DbType="NVarChar(63) NOT NULL" CanBeNull="false" />
      <Column Name="Country" Type="System.String" DbType="NVarChar(31) NOT NULL" CanBeNull="false" />
      <Column Name="ZipCode" Type="System.String" DbType="NVarChar(7) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="User_Borrowing" Member="Borrowings" ThisKey="Id" OtherKey="UserId" Type="Borrowing" />
    </Type>
  </Table>
  <Table Name="dbo.Spoznieni" Member="Spoznienis">
    <Type Name="Spoznieni">
      <Column Name="Firstname" Type="System.String" DbType="NVarChar(63) NOT NULL" CanBeNull="false" />
      <Column Name="Lastname" Type="System.String" DbType="NVarChar(63) NOT NULL" CanBeNull="false" />
      <Column Name="CopyId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ReturnDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(63) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.wypozyczenia" Member="wypozyczenias">
    <Type Name="wypozyczenia">
      <Column Name="Firstname" Type="System.String" DbType="NVarChar(63) NOT NULL" CanBeNull="false" />
      <Column Name="Lastname" Type="System.String" DbType="NVarChar(63) NOT NULL" CanBeNull="false" />
      <Column Name="CopyId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ReturnDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(63) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.AuthorList" Member="AuthorLists">
    <Type Name="AuthorList">
      <Column Name="AuthorId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BookId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="Author_AuthorList" Member="Author" ThisKey="AuthorId" OtherKey="Id" Type="Author" IsForeignKey="true" />
      <Association Name="Book_AuthorList" Member="Book" ThisKey="BookId" OtherKey="Id" Type="Book" IsForeignKey="true" />
    </Type>
  </Table>
</Database>